### PR TITLE
PHP 8.0 support

### PR DESCRIPTION
**Pull request by joseluisq**
This PR adds PHP 8.0 support.
It was tested successfully with PHP 8.0 via Docker.

```sh
docker run --rm -it -v $PWD:/var/www/html joseluisq/php-fpm:8.0 \
  sh -c 'composer install && vendor/bin/phpunit'
```

Note: PHP 8.1 support could come later via a new PR.

### CODE REVIEW

**Comment by joseluisq** [comment]
@ssheduardo here is the initial draft PR for adding PHP 8.0. It works in general with just a minor fix on the tests.
But it is necessary to bump up to 7.4 as the minimum PHP version required via `composer.json`.

PHP 8.1 will give more test problems but they can be solved in a second PR.

**Comment by ssheduardo** [comment]
Hola, tienes algún correo u otro medio para comunicarme contigo?

**Comment by ssheduardo** [comment]
Hi,
When run the command:
```
docker run --rm -it -v $PWD:/var/www/html joseluisq/php-fpm:8.0 \
  bash -c 'composer install && vendor/bin/phpunit'
```
The docker response:
image

But if I change bash to sh, the command no show the error.

image

Run test is OK

**Comment by joseluisq** [comment]
> Hola, tienes algún correo u otro medio para comunicarme contigo?

Puede usar mi cuenta Keybase para chat directo. https://joseluisq.net my usuario es joseluisq

**Comment by joseluisq** [comment]
> But if I change bash to sh, the command no show the error.

Yes, fixed in the description.

**Pull request merged**
